services:
  vpn:
    build:
      dockerfile: Dockerfile
    privileged: true
    volumes:
      # https://github.com/adrienverge/openfortivpn/blob/master/doc/openfortivpn.1.in
      - ./config:/etc/openfortivpn:ro
#      - /etc/resolv.conf:/etc/resolv.conf
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=1
#      - net.ipv6.conf.default.disable_ipv6=1
#      - net.ipv6.conf.lo.disable_ipv6=1
    restart: always

  proxy:
    ports:
      - 127.0.0.1:10443:10443
    image: nadoo/glider
    volumes:
      - ./domain.rule:/app/domain.rule
    entrypoint:
      - /app/glider
#      - --verbose
      - --listen=:10443
      - --rulefile=domain.rule
    depends_on:
      - vpn
    restart: always